apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: noam-rollout-reporter
  namespace: aws-local-runtime
spec:
  eventBusName: codefresh-eventbus
  resource:
    analysisruns:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      resource: analysisruns
      version: v1alpha1
      cluster: noam
    replicasets:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: apps
      resource: replicasets
      version: v1
      cluster: noam
    rollouts:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      resource: rollouts
      version: v1alpha1
      cluster: noam
  template:
    container:
      name: ''
      resources: {}
    serviceAccountName: rollout-reporter-sa
status: {}
