apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: arn-aws-eks-us-east-1-705921569962-cluster-noam-test
spec:
  destination:
    namespace: default
    server: https://50826B3061FFA59FB675CA2B21345854.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    directory:
      include: '{all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/aws-local-runtime/*.yaml,runtimes/aws-local-runtime/**/*.yaml}'
      recurse: true
    path: shared-config/resources
    repoURL: https://github.com/PhilippPlotnikov/aws-local-runtime.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
