apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=http://5e11-77-223-69-165.ngrok.io
  - cors=http://5e11-77-223-69-165.ngrok.io
  - env=production
  name: cap-app-proxy-cm
kind: Kustomization
namespace: aws-local-runtime
resources:
- ../../base
- ingress.yaml
