apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: philipp-test-rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: csdp
  source:
    repoURL: https://github.com/codefresh-io/csdp-official.git
    path: csdp/base/argo-rollouts
    targetRevision: latest-managed
  destination:
    namespace: default
    server: https://19208D3B75E55C7C01C2906505D2B475.gr7.us-east-1.eks.amazonaws.com
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
